### ISSUE TITLE
Не работает OrderingFilter на генерации схемы

### ISSUE THREAD

**Issue by stepan-fedorovv** [best-doctor/restdoctor#186]
https://github.com/best-doctor/restdoctor/blob/master/restdoctor/rest_framework/schema/filters.py#L77

```python
FILTER_MAP: FilterMap = {
    BooleanFilter: {'type': 'boolean'},
    ChoiceFilter: _get_filter_schema_choice,
    MultipleChoiceFilter: _get_filter_schema_choice,
    TypedChoiceFilter: _get_filter_schema_choice,
    TypedMultipleChoiceFilter: _get_filter_schema_choice,
    DateFilter: functools.partial(_get_filter_schema_datetime, schema_format='date'),
    DateFromToRangeFilter: functools.partial(_get_filter_schema_datetime, schema_format='date'),
    DateTimeFilter: functools.partial(_get_filter_schema_datetime, schema_format='date-time'),
    DateTimeFromToRangeFilter: functools.partial(
        _get_filter_schema_datetime, schema_format='date-time'
    ),
    NumberFilter: {'type': 'number'},
    TimeFilter: functools.partial(_get_filter_schema_datetime, schema_format='time'),
    ModelChoiceFilter: {'type': 'string'},
    ModelMultipleChoiceFilter: {'type': 'string'},
}
```
python 3.12, restdoctor 0.0.64

схема генерируется с ошибками при создании кастомного OrderingFilter

```yaml
      - name: ordering
        required: false
        in: query
        description: !!python/object/apply:django.utils.functional._lazy_proxy_unpickle
        - !!python/name:django.utils.translation.gettext ''
        - !!python/tuple
          - Ordering
        - {}
        - !!python/name:builtins.str ''
        schema:
          type: string
          enum:
          - ''
          - start_time
          - -start_time
          - members
          - -members
```

атрибут description выдает ошибку при сборке через шаблон swagger

manage:  `python ./manage.py generateschema --urlconf configuration.urls --generator_class restdoctor.rest_framework.schema.RefsSchemaGenerator > apps/user/static/static_docs/api/openapi.schema`

swagger error:
```
Parser error on line 373
unknown tag !<tag:yaml.org,2002:python/name:django.utils.translation.gettext>
```
